---
title: "Face Recognition Analysis among College Students of India"
author: "Rishi Dey Chowdhury"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Abstract

Data collected from college students of India, composed mainly of students of Indian Statistical Institute was analyzed for their face recognition ability based on their response in a Face Recognition Questionnaire Survey. Several interesting relation between the facial and social variables and domains were found out. We find the psychological connection between different aspects of human face with communication, beauty and preferences in society among students.

# Acknowledgement

This study is a project as a part of Face Recognition Study, using statistical techniques, in my psychology course. It wouldn't have been possible without the constant support of my friends and resources to turn the idea I had in mind into a finished detailed report. I would also like to thank my psychology Prof. Debdulal Dutta Roy, for choosing such an important topic for this project which has great essence in today's world, where face is a very important means of communication.

Finally, I would also say that it was the outcome of constant efforts and dedication of proper time from my side that played the pivotal and most important role in completing this thorough detailed study.

By,

Rishi Dey Chowdhury(BS2044)

Indian Statistical Institute, Kolkata

# Introduction

Faces convey a wealth of information that is critical to social interactions, such as identity and emotion. Moreover, because all faces contain the same features (eyes, nose, mouth) in the same general
configuration (eyes above nose, nose above mouth), distinguishing between individuals is a visually demanding task. Despite this, we are able to recognize individuals across a variety of superficial perceptual changes in lighting or viewpoint. Face recognition is critical to social interaction and it has received extensive attention from researchers using a range of methods.
A human face reveals a great deal of information to a perceiver. It can tell about mood and intention and attentiveness, but it can also serve to identify a person. Of course, a person can be identified by other means than the face. Voice, body shape, gait or even clothing may all establish identity in circumstances where facial detail may not be available. Nevertheless, a face is the most distinctive and widely used key to a person's identity, and the loss of ability to recognize faces experienced by some neurological (prosopagnosic) patients has a profound effect on their lives.
Here, we explore some of the psychological aspect of how faces are related by humans to beauty standards, commnication, familiarity and how human beings perceives faces and which facial or face related features are preferred by most of the students in the society.

## Objective

The motive of conducting this study is mentioned below-

-   Finding out the **overall face recognition ability among the college students of India** and visualizing the results.

-   Understanding the underlying **correlation between the items(or questions asked) by different domains or aspects of face recognition**(see next section).

-   Understanding the underlying **correlation between the different domains of face recognition**.

-   Finding out the domains and item's connection with the way faces are percieved by the society.

-   Observing the trend in the response like the **composition of the overall face recognition score**.

## Importance

Studies like this is very important in understanding the face recognition ability in psychology. Some reasons of why such studies are of great importance are as follows-

-   **Human faces are a very important mean to communicate and interact with others, understanding how human faces are percieved by society would help us know the importance of interacting face to face**

-   Understanding the **the preferences of some facial features and overall looks over other, so as to erradiate any bias**.

-   Helps in understanding **human-human interaction**.

-   Better **understand the variables involved in study** which can be as complex as social understanding, attention and perception, memory etc.

# Literature Review

The human face is a very important visual stimulus in the human experiential world. It is a powerful social stimulus and is also responsible for drawing inferences about individuals we come across in our day to day lives. Information can be gained from both its static form and also its dynamic form the human face. Human faces are able to capture attention more easily than other objects (Ro, Russell & Lavie, 2001). Additionally, it is believed that facial images also facilitate subsequent processing at the locations where they occur (Axelrod, Bar & Rees, 2015). People also tend to make faster and greater accurate responses with regard to their own faces than in comparison to the faces of familiar others (Sui, Liu & Hans, 2009; Tong & Nakayama, 1999).\
Human beings tend to infer about individual's sex, race and age effortlessly and automatically from their faces ( Macrae & Bodenhausen, 2000). These implications are based upon multiple features including hair, shape of face, the eyes and brows and even mouth (Brown & Perrett, 1993; Roberts & Bruce, 1988). Thus, facial features play a crucial role behind overall face perception. Another important aspect in this regard is related to memory. Memory works more in the domain of identification and recognition of human faces. Mostly all faces consist of similar features (eyes, nose and mouth) in the same configuration. Hence distinguishing among faces and recognizing them correctly becomes a very visually demanding task. Despite this we are able to identity /recognize individuals across a variety of environmental settings.\
Our faces also play a key role in mate selection and interpersonal relationships. Often biases exist in terms of which face we find attractive. Attractive people are also considered as more extroverted with higher level of self-esteem and enhanced social skills (Langlois et al.,2000). Based on the above evidences, the domains of memory, social understanding, attention, perception and facial features have been incorporated in the questionnaire for face recognition.
